version: "2.1"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-standalone
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=tes
         - POSTGRES_USER=postgres
         - POSTGRES_DB=tourspel
    healthcheck:
       test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
       interval: 5s
       timeout: 1s
       retries: 2
# APP*****************************************
  tourapp:
    image: tourapp:latest
    network_mode: bridge
    container_name: tourapp
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - postgres
