micronaut:
  application:
    name: tourapp
  server:
    port: 2019



---

datasources:
  default:
    url: jdbc:postgresql://localhost:32769/tour
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        show_sql: true
#flyway:
 # datasources:
  #  default:
   #   locations: classpath:dbmigrations
---

datasources.default: {}

---

#graphql:
#  graphiql.enabled: true
