micronaut:
  application:
    name: tourapp
  server:
    port: 2019


---

datasources:
  default:
    url: jdbc:postgresql://ec2-174-129-254-223.compute-1.amazonaws.com:5432/d1f4aadqcknre8
    username: uuefbvthsfpaav
    password: b38a168974c145fe6fbd85856c1e7cee491f45bbaea2aace382d2d3b9cd4cbd8
    driverClassName: org.postgresql.Driver
    sslmode: require
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:dbmigrations
---

datasources.default: {}

---

#graphql:
#  graphiql.enabled: true
