micronaut:
  application:
    name: tourapp
  server:
    port: 2019



---

datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5432/tourspel
    username: postgres
    password: tes
    driverClassName: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:dbmigrations
---

datasources.default: {}

---

#graphql:
#  graphiql.enabled: true
